### ISSUE TITLE
Readme is missing command in execution instructions

### ISSUE THREAD

**Issue by snake14** [matomo-org/matomo-scoper#4]
While trying to use the scoper, I found that there's a typo in [the execution instructions](https://github.com/matomo-org/matomo-scoper/blob/main/README.md?plain=1#L31). I had to use the `--help` option to figure out that I needed to include the `scope` command like `./bin/matomo-scoper scope /path/to/plugin`

**Comment by diosmosis** [comment]
scope is the default command, it shouldn't be needed to specify it if you don't want to

**Comment by snake14** [comment]
That's odd, because it didn't use the default when I tried in Ubuntu 22.04:
![image](https://github.com/matomo-org/matomo-scoper/assets/11394099/4deb07ac-530a-45ed-918d-587e1d47111e)
It worked fine when I included the command:
![image](https://github.com/matomo-org/matomo-scoper/assets/11394099/4944e346-84fe-470b-84bc-af17b8dd30c1)

**Comment by diosmosis** [comment]
I see, I guess symfony console doesn't fall back to the default command.
